version: '3.8'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build: 
      context: ./BlogNews
      dockerfile: Dockerfile.prod
    command: gunicorn blognews.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env.prod.db

volumes:
  mysql_data:
  static_volume:
  media_volume:
