version: 3.8

services:
  web:
    build: .
    command: gunicorn blognews.wsgi.application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      db
  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env.prod.db

volumes:
  mysql_data:
