# Generated by Django 4.0.4 on 2022-07-08 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import post.types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=50, verbose_name='título')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=50, verbose_name='título')),
                ('excerpt_post', models.TextField(max_length=300, verbose_name='excerto')),
                ('description_post', models.TextField(verbose_name='descrição')),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='post/%Y/%m/', verbose_name='Imagem')),
                ('anonymous_views_post', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('user_views_post', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('published_post', models.BooleanField(default=True, verbose_name='publicado')),
                ('published_date_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de publicação')),
                ('edition_date_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de edição')),
                ('album_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.album', verbose_name='Album')),
                ('category_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='Categoria')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='RattingUserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratting', post.types.RattingField(verbose_name='avaliação')),
                ('post_ratting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='post')),
                ('user_ratting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
            },
        ),
        migrations.AddConstraint(
            model_name='rattinguserpost',
            constraint=models.UniqueConstraint(fields=('user_ratting', 'post_ratting'), name='ratting_user_post'),
        ),
    ]
