# Generated by Django 4.0.4 on 2022-06-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt_post',
            field=models.TextField(max_length=300, verbose_name='excerto'),
        ),
    ]
