# Generated by Django 4.0.4 on 2022-06-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_views_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views_post',
            new_name='anonymous_views_post',
        ),
        migrations.AddField(
            model_name='post',
            name='user_views_post',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
    ]
