# Generated by Django 4.0.4 on 2022-06-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_views_post_post_anonymous_views_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ratting_post',
        ),
    ]
