# Generated by Django 4.0.4 on 2022-06-15 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_ratting_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edition_date_post',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de edição'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date_post',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de publicação'),
        ),
    ]
