# Generated by Django 4.0.4 on 2022-06-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_edition_date_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rattinguserpost',
            options={'verbose_name': 'avaliação', 'verbose_name_plural': 'avaliações'},
        ),
        migrations.AddConstraint(
            model_name='rattinguserpost',
            constraint=models.UniqueConstraint(fields=('user_ratting', 'post_ratting'), name='ratting_user_post'),
        ),
    ]
