# Generated by Django 4.0.4 on 2022-07-17 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletteruser_creation_date_newsletteruser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='activated_date_newsletteruser',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 4, 56, 406327), verbose_name='data de ativação'),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='creation_date_newsletteruser',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 4, 56, 406327), verbose_name='data de criação'),
        ),
    ]
