# Generated by Django 4.0.4 on 2022-07-17 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletteruser_activated_date_newsletteruser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_newslettermessage', models.TextField(verbose_name='mensagem')),
                ('creation_date_newslettermessage', models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 34, 42, 865195), verbose_name='data de criação')),
                ('edition_date_newslettermessage', models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 34, 42, 865195), verbose_name='última edição')),
                ('published_newslettermessage', models.BooleanField(default=False, verbose_name='publicado')),
            ],
        ),
        migrations.AlterModelOptions(
            name='newsletteruser',
            options={'verbose_name': 'usuário'},
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='activated_date_newsletteruser',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 34, 42, 865195), verbose_name='data de ativação'),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='creation_date_newsletteruser',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 34, 42, 865195), verbose_name='data de criação'),
        ),
    ]
