# Generated by Django 4.0.4 on 2022-07-17 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newslettermessage_alter_newsletteruser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettermessage',
            options={'verbose_name': 'mensagem', 'verbose_name_plural': 'mensagens'},
        ),
        migrations.AddField(
            model_name='newslettermessage',
            name='title_newslettermessage',
            field=models.CharField(default='teste', max_length=998, verbose_name='título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newslettermessage',
            name='creation_date_newslettermessage',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 46, 38, 820203), verbose_name='data de criação'),
        ),
        migrations.AlterField(
            model_name='newslettermessage',
            name='edition_date_newslettermessage',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 46, 38, 820203), verbose_name='última edição'),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='activated_date_newsletteruser',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 46, 38, 820203), verbose_name='data de ativação'),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='creation_date_newsletteruser',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 46, 38, 820203), verbose_name='data de criação'),
        ),
    ]
