# Generated by Django 4.0.4 on 2022-12-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreportregister',
            options={'verbose_name': 'denúncias do usuário', 'verbose_name_plural': 'denúncias dos usuários'},
        ),
    ]
