# Generated by Django 4.0.4 on 2024-01-28 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('w', 'Aguardando'), ('a', 'Aprovado'), ('r', 'Rejeitado')], default='w', max_length=1, verbose_name='situação')),
                ('description', models.TextField(verbose_name='descrição')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'denúncia',
            },
        ),
    ]
