# Generated by Django 4.0.4 on 2022-07-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'denúncia'},
        ),
    ]
