# Generated by Django 4.0.4 on 2022-06-30 22:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VottingUserSearchOption',
            new_name='VottingUserSearch',
        ),
    ]
