# Generated by Django 4.0.4 on 2022-06-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'alternativa'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'pesquisa'},
        ),
        migrations.AlterField(
            model_name='option',
            name='vote_option',
            field=models.PositiveIntegerField(default=0, verbose_name='número de votos'),
        ),
    ]
