# Generated by Django 4.0.4 on 2022-06-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_vottingusersearchoption_vottingusersearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VottingUserSearch',
        ),
    ]
