# Generated by Django 4.0.4 on 2022-06-30 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0003_delete_vottingusersearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='VottingUserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_votting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.option', verbose_name='alternativa')),
                ('search_votting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search', verbose_name='pesquisa')),
                ('user_votting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'voto',
            },
        ),
        migrations.AddConstraint(
            model_name='vottingusersearch',
            constraint=models.UniqueConstraint(fields=('user_votting', 'search_votting'), name='user_search_vote'),
        ),
    ]
