# Generated by Django 4.0.4 on 2022-07-01 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0004_vottingusersearch_vottingusersearch_user_search_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='VottingUserOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_votting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.option', verbose_name='alternativa')),
                ('user_votting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'voto',
            },
        ),
        migrations.DeleteModel(
            name='VottingUserSearch',
        ),
        migrations.AddConstraint(
            model_name='vottinguseroption',
            constraint=models.UniqueConstraint(fields=('user_votting', 'option_votting'), name='user_option_vote'),
        ),
    ]
