# Generated by Django 4.0.4 on 2022-07-08 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date_comment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de publicação')),
                ('edition_date_comment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima edição')),
                ('comment', models.TextField(max_length=200, verbose_name='comentário')),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='post')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'comentário',
                'verbose_name_plural': 'comentários',
            },
        ),
    ]
