# Generated by Django 4.0.4 on 2022-06-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='published_comment',
        ),
    ]
