# Generated by Django 4.0.4 on 2022-06-15 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_comment_published_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edition_date_comment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ultima edição'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published_date_comment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de publicação'),
        ),
    ]
